# Generated by Django 5.1.6 on 2025-03-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_artigos_sumario_alter_artigos_data_comentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artigos',
            new_name='Articles',
        ),
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comment',
        ),
    ]
